#!/usr/bin/env bash
#
# build-deb.sh — build dist/zlinuxdocs_<version>_all.deb from a clean checkout.
#
# No make, no dpkg-buildpackage, no dh_*, no pip, no network. Exits non-zero on
# any failure. Prints the artifact path on success.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

STAGE="$ROOT/staging"
DIST="$ROOT/dist"

die() { printf 'build-deb.sh: FATAL: %s\n' "$*" >&2; exit 1; }
step() { printf '==> %s\n' "$*"; }

# --- 1. version, single-sourced ---------------------------------------------
step "reading VERSION"
[ -f VERSION ] || die "VERSION file is missing"
VERSION="$(tr -d ' \t\n\r' < VERSION)"
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || die "VERSION '$VERSION' is not X.Y.Z"
echo "    version = $VERSION"

# --- 2. toolchain ------------------------------------------------------------
for t in dpkg-deb python3 gzip sed find; do
  command -v "$t" >/dev/null 2>&1 || die "'$t' is required to build but is not installed"
done

# --- 2b. the build clock -----------------------------------------------------
# One timestamp for the whole build, so two builds of the same source produce a
# byte-identical .deb. SOURCE_DATE_EPOCH is honoured if set (the
# reproducible-builds convention). Otherwise the RELEASE TAG's date is used —
# it is immutable, so v<VERSION> rebuilds to the same bytes however many
# commits land afterwards — then the last commit, then a fixed constant.
if [ -z "${SOURCE_DATE_EPOCH:-}" ]; then
  SOURCE_DATE_EPOCH="$(git -C "$ROOT" log -1 --format=%ct "v$VERSION" 2>/dev/null || true)"
fi
if [ -z "${SOURCE_DATE_EPOCH:-}" ]; then
  SOURCE_DATE_EPOCH="$(git -C "$ROOT" log -1 --format=%ct 2>/dev/null || true)"
fi
[ -n "${SOURCE_DATE_EPOCH:-}" ] || SOURCE_DATE_EPOCH=1735689600   # 2025-01-01Z
export SOURCE_DATE_EPOCH
echo "    SOURCE_DATE_EPOCH = $SOURCE_DATE_EPOCH"

# --- 3. clean ----------------------------------------------------------------
step "cleaning previous build"
rm -rf "$STAGE"
mkdir -p "$DIST"
mkdir -p "$STAGE/DEBIAN" \
         "$STAGE/usr/bin" \
         "$STAGE/usr/share/zlinuxdocs" \
         "$STAGE/usr/share/man/man1" \
         "$STAGE/usr/share/doc/zlinuxdocs"

# --- 4. example documents ----------------------------------------------------
# The checked-in copies are staged as-is, so two builds of the same source
# stage identical bytes. They are regenerated ONLY when one is missing or when
# --regen-samples is asked for, because python-docx stamps the current time
# into the .docx zip and would otherwise make every build differ.
REGEN=0
[ "${1:-}" = "--regen-samples" ] && REGEN=1
missing=0
while IFS= read -r name; do
  [ -f "share/samples/$name" ] || missing=1
done < <(python3 -c 'import sys; sys.path.insert(0, "tools"); import make_samples; [print(n) for n, _ in make_samples.SAMPLES]')
if [ "$REGEN" -eq 1 ] || [ "$missing" -eq 1 ]; then
  step "generating the example documents"
  python3 tools/make_samples.py "$ROOT/share/samples" >/dev/null \
    || die "the example documents could not be generated"
else
  step "staging the checked-in example documents (--regen-samples rebuilds them)"
fi

# --- 5. entry script ---------------------------------------------------------
step "installing the entry script"
[ -f bin/zlinuxdocs ] || die "bin/zlinuxdocs is missing"
install -m 0755 bin/zlinuxdocs "$STAGE/usr/bin/zlinuxdocs"
# Short alias. A relative symlink so it survives any install prefix.
ln -sf zlinuxdocs "$STAGE/usr/bin/zld"

# --- 6. python package -------------------------------------------------------
step "installing the program"
cp -r zlinuxdocs "$STAGE/usr/share/zlinuxdocs/zlinuxdocs"

# --- 7. version stamp (generated, never hand-edited in the artifact) ---------
step "stamping the version"
cat > "$STAGE/usr/share/zlinuxdocs/zlinuxdocs/__version__.py" <<EOF
# GENERATED by build-deb.sh from the repo-root VERSION file. Do not edit.
__version__ = "$VERSION"
EOF
SRC_VERSION="$(python3 - <<'PY'
import re, io
src = io.open("zlinuxdocs/__version__.py", encoding="utf-8").read()
m = re.search(r'__version__\s*=\s*"([^"]+)"', src)
print(m.group(1) if m else "")
PY
)"
[ "$SRC_VERSION" = "$VERSION" ] || \
  die "zlinuxdocs/__version__.py says '$SRC_VERSION' but VERSION says '$VERSION' — fix the source file"

# --- 8. vendored libraries ---------------------------------------------------
step "installing the vendored libraries"
[ -d vendor/docx ] || die "vendor/docx is missing (python-docx was not vendored)"
[ -d vendor/yaml ] || die "vendor/yaml is missing (PyYAML was not vendored)"
[ -d vendor/pypdf ] || die "vendor/pypdf is missing (pypdf was not vendored)"
[ -f vendor/typing_extensions.py ] || die "vendor/typing_extensions.py is missing"
cp -r vendor "$STAGE/usr/share/zlinuxdocs/vendor"
for lic in vendor/docx/LICENSE vendor/yaml/LICENSE vendor/pypdf/LICENSE vendor/typing_extensions.LICENSE; do
  [ -f "$lic" ] || die "$lic is missing — vendored code must ship its licence"
done

# --- 9. samples + profiles ---------------------------------------------------
step "installing the examples and the print profile"
mkdir -p "$STAGE/usr/share/zlinuxdocs/samples" "$STAGE/usr/share/zlinuxdocs/profiles"
cp share/samples/*.docx "$STAGE/usr/share/zlinuxdocs/samples/"
cp share/samples/README.md "$STAGE/usr/share/zlinuxdocs/samples/"
cp share/profiles/*.yaml "$STAGE/usr/share/zlinuxdocs/profiles/"
n_samples="$(find "$STAGE/usr/share/zlinuxdocs/samples" -name '*.docx' | wc -l)"
[ "$n_samples" -ge 2 ] || die "only $n_samples example document(s) staged; at least 2 are required"

# --- 10. man page ------------------------------------------------------------
step "installing the manual page"
sed "s/@VERSION@/$VERSION/g" man/man1/zlinuxdocs.1 > "$STAGE/usr/share/man/man1/zlinuxdocs.1"
gzip -9n "$STAGE/usr/share/man/man1/zlinuxdocs.1"
ln -sf zlinuxdocs.1.gz "$STAGE/usr/share/man/man1/zld.1.gz"

# --- 11. control -------------------------------------------------------------
step "writing DEBIAN/control"
sed "s/VERSION_PLACEHOLDER/$VERSION/" debian/control > "$STAGE/DEBIAN/control"
chmod 0644 "$STAGE/DEBIAN/control"
grep -q "^Version: $VERSION$" "$STAGE/DEBIAN/control" \
  || die "the Version field was not substituted correctly"

# --- 12. changelog + copyright + readme -------------------------------------
step "writing the documentation files"
DATE_RFC="$(LC_ALL=C date -u -d "@$SOURCE_DATE_EPOCH" '+%a, %d %b %Y %H:%M:%S +0000')"
sed -e "s/@VERSION@/$VERSION/g" -e "s/@DATE@/$DATE_RFC/g" debian/changelog.in \
  > "$STAGE/usr/share/doc/zlinuxdocs/changelog.Debian"
gzip -9n "$STAGE/usr/share/doc/zlinuxdocs/changelog.Debian"
cp debian/copyright "$STAGE/usr/share/doc/zlinuxdocs/copyright"
cp README.md "$STAGE/usr/share/doc/zlinuxdocs/README.md"

# --- 13. smoke-test the staged program ---------------------------------------
# Runs BEFORE the cruft strip, because running Python writes __pycache__ and
# that must not survive into the package. PYTHONDONTWRITEBYTECODE is belt and
# braces; the strip below is the braces.
step "smoke-testing the staged program"
staged_version="$(PYTHONDONTWRITEBYTECODE=1 "$STAGE/usr/bin/zlinuxdocs" --version)"
[ "$staged_version" = "zlinuxdocs $VERSION" ] \
  || die "the staged program reports '$staged_version', expected 'zlinuxdocs $VERSION'"
PYTHONDONTWRITEBYTECODE=1 "$STAGE/usr/bin/zlinuxdocs" inspect \
  "$STAGE/usr/share/zlinuxdocs/samples/proper-headings.docx" >/dev/null \
  || die "the staged program cannot read its own example document"

# --- 14. strip build cruft ---------------------------------------------------
step "stripping build cruft"
find "$STAGE" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true
find "$STAGE" -name '*.pyc' -delete
find "$STAGE" -name '.git*' -maxdepth 6 -exec rm -rf {} + 2>/dev/null || true

# --- 15. verify the staging tree --------------------------------------------
step "verifying the staging tree"
[ -x "$STAGE/usr/bin/zlinuxdocs" ] || die "/usr/bin/zlinuxdocs is not executable"
[ -L "$STAGE/usr/bin/zld" ] || die "/usr/bin/zld symlink is missing"
[ -f "$STAGE/usr/share/zlinuxdocs/zlinuxdocs/cli.py" ] || die "the program files are missing"
[ -f "$STAGE/usr/share/zlinuxdocs/vendor/docx/__init__.py" ] || die "the vendored python-docx is missing"

n_cruft="$(find "$STAGE" \( -name '__pycache__' -o -name '*.pyc' \) | wc -l)"
[ "$n_cruft" -eq 0 ] || die "$n_cruft __pycache__/.pyc item(s) leaked into the package"

# Normalise modes: dirs 755, files 644, the entry script 755. Whatever umask
# the builder happened to have must not reach the package.
find "$STAGE" -type d -exec chmod 0755 {} +
find "$STAGE" -type f -exec chmod 0644 {} +
chmod 0755 "$STAGE/usr/bin/zlinuxdocs"

# Now assert it: no file in the package may be group- or world-writable.
bad_perm="$(find "$STAGE" -type f -perm /022 -print | head -5 || true)"
[ -z "$bad_perm" ] || die "these files are group/world writable: $bad_perm"

# There must be no maintainer scripts. This is a deliberate policy: nothing
# executes on install or removal.
for s in preinst postinst prerm postrm config; do
  [ ! -e "$STAGE/DEBIAN/$s" ] || die "a maintainer script ($s) was staged; this package ships none"
done

# md5sums, so `debsums zlinuxdocs` can tell the user whether their install is
# intact. Paths are relative to / and sorted, so the file is reproducible.
step "writing DEBIAN/md5sums"
( cd "$STAGE" && find . -type f -not -path './DEBIAN/*' -printf '%P\0' \
    | sort -z | xargs -0 md5sum ) > "$STAGE/DEBIAN/md5sums"
chmod 0644 "$STAGE/DEBIAN/md5sums"
n_md5="$(wc -l < "$STAGE/DEBIAN/md5sums")"
[ "$n_md5" -gt 100 ] || die "md5sums lists only $n_md5 files; that cannot be right"
echo "    $n_md5 files checksummed"

# --- 15. build ---------------------------------------------------------------
step "normalising timestamps to $SOURCE_DATE_EPOCH (reproducible build)"
find "$STAGE" -exec touch --no-dereference --date="@$SOURCE_DATE_EPOCH" {} +

DEB="$DIST/zlinuxdocs_${VERSION}_all.deb"
step "building $DEB"
rm -f "$DEB"
dpkg-deb --build --root-owner-group --uniform-compression "$STAGE" "$DEB" >/dev/null

# --- 16. verify the artifact -------------------------------------------------
step "verifying the artifact"
# Capture once — piping dpkg-deb into `grep -q` makes grep exit early and kills
# dpkg-deb with SIGPIPE, which pipefail then reports as a build failure.
DEB_INFO="$(dpkg-deb -I "$DEB")"
DEB_LIST="$(dpkg-deb -c "$DEB")"

grep -qE '^ Package: zlinuxdocs$'   <<<"$DEB_INFO" || die "the Package field is wrong"
grep -qE "^ Version: $VERSION$"     <<<"$DEB_INFO" || die "the Version field is wrong"
grep -qE '^ Architecture: all$'     <<<"$DEB_INFO" || die "the Architecture field is wrong"
grep -qE '^ Depends: '              <<<"$DEB_INFO" || die "the Depends field is missing"
grep -q 'usr/bin/zlinuxdocs'                <<<"$DEB_LIST" || die "the entry script is missing from the .deb"
grep -q 'usr/bin/zld'                       <<<"$DEB_LIST" || die "the zld alias is missing from the .deb"
grep -q 'usr/share/zlinuxdocs/samples/'     <<<"$DEB_LIST" || die "the examples are missing from the .deb"
grep -q 'usr/share/zlinuxdocs/vendor/docx/' <<<"$DEB_LIST" || die "the vendored libraries are missing"
grep -q 'usr/share/man/man1/zlinuxdocs.1.gz' <<<"$DEB_LIST" || die "the manual page is missing"
grep -q 'usr/share/doc/zlinuxdocs/copyright' <<<"$DEB_LIST" || die "the copyright file is missing"
grep -q 'usr/bin/zld -> zlinuxdocs'          <<<"$DEB_LIST" || die "the zld symlink does not point at zlinuxdocs"
! grep -q '__pycache__\|\.pyc' <<<"$DEB_LIST" || die "__pycache__/.pyc leaked into the .deb"

CTRL="$(dpkg-deb --ctrl-tarfile "$DEB" | tar -t)"
grep -qx './control' <<<"$CTRL" || die "the control file is missing from the control archive"
grep -qx './md5sums' <<<"$CTRL" || die "md5sums is missing from the control archive"
for s in preinst postinst prerm postrm config; do
  ! grep -qx "./$s" <<<"$CTRL" || die "a maintainer script ($s) reached the .deb"
done

n_deb_samples="$(grep -c 'usr/share/zlinuxdocs/samples/.*\.docx' <<<"$DEB_LIST" || true)"
[ "$n_deb_samples" -ge 2 ] || die "only $n_deb_samples example document(s) in the .deb"
echo "    $n_deb_samples example documents included"

echo
grep -E '^ (Package|Version|Architecture|Depends|Recommends|Installed-Size):' <<<"$DEB_INFO"
echo
echo "$DEB"
